metricq/metricq-python

.vscode/settings.json, metricq/types.py, tests/type_test.py
Added `precise_string` function to `Timedelta` for pretty printing of values without loss of precision. -> You can parse it again using `Timedelta.from_string` and you will receive the original `Timedelta`.
Tests included in "tests" folder.
Fixes Issue #27
=> Issue 27 - Precise and Pretty Timedelta

.github/workflows/pythonpackage.yml
Split the release job in a `build` and `upload` (aka `release`) step
Fixes #34
~TODO: rename jobs after #36 is merged~
=> Split release job

pyproject.toml, setup.cfg, tools/metricq-discover.py, tools/metricq-spy.py
This mostly affects `metricq-discover.py`:
* use humanize to print human-readable durations
* print client status first
* add `--timeout` to specify maximum time spent waiting for responses
* add `--ignore` to ignore error responses
=> Improve output of sample tools

.pre-commit-config.yaml, docs/api/history-client.rst, docs/howto/history-client.rst, docs/howto/index.rst, docs/howto/metric-lookup.rst, docs/index.rst, metricq/client.py, metricq/history_client.py, setup.cfg, tests/test_history_client.py
Add a few shorthand methods to `HistoryClient` that are easier to work with than `history_data_request()`.
All `HistoryRequestType`s should have a corresponding method, except maybe `FLEX_TIMELINE`. It's returned values are either aggregates or values, so not much is gained by unwrapping the received `HistoryResponse`.
Closes #56.
TODO:
=> Add history request convenience methods

tools/metricq-spy.py
7998efdf0b0d26e0b0631b9a029f8355d271b0ea changed the default behavior of 
get_metrics
=> Fixes missing non-historic metrics in metricq spy

.github/workflows/changelog.yml
set-env isn't allowed anymore.
For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
=> fix(ci): Fix changelog workflow

.github/workflows/pythonpackage.yml, setup.cfg
SSL is sometimes broken in python 3.7 preventing clients from stopping. So we require python 3.8
=> Require python 3.8 for ssl fixes

docs/metadata.rst, metricq/source.py, metricq/source_metric.py, metricq/types.py, tests/test_source.py, tests/test_source_metric.py
This fixes #65 by adding "chunkSize" to the metadata of each metric before sending the `source.declare_metrics` RPC.
Technically, this introduces a **breaking change** (so I marked it as 2.0.0):
* 4dc2190: `chunk_size` is validated before assignment, that may raise an exception. Assigning `0` instead of `None` is now an error, where before it was silently converted
Some minor issues that I originally found here moved to #74.
=> Augment "chunkSize" to metadata when declaring new metrics

metricq/history_client.py, metricq/types.py, tests/test_types.py
This implements/resolves #76.
Todo:
- deprecate `integral`, document accordingly
- add `integral_s`/`integral_ns`
- document all new properties
=> Fix TimeAggregate member types

MANIFEST.in, metricq/history_client.py, tests/test_history_client.py
We need to propagate error messages from the DBs to the clients. This should do it.
Fixes #62
=> Handle error messages in history responses

metricq/history_client.py
When handling history responses, the response future in `future` might be unbound in the `HistoryError` handler.
Split this in three steps to reduce error handling clutter:
1. Obtain future from correlation ID, which is possibly unknown
2. Check that this future is not already done, i.e. the response was not handled already
3. Parse history response, set result or exception of the response future accordingly
=> Prevent possibly unbound variable in history response handler

metricq/interval_source.py, tests/test_interval_source.py
This fixes #81.
Currently based on #82, needs to be rebased once that is merged.
=> Make `IntervalSource.period` a `Timedelta`

docs/conf.py, metricq/types.py, setup.py, tests/test_types.py
=> Properly parse ISO 8601 date strings to Timestamp

metricq/interval_source.py, tests/test_interval_source.py
Resetting `IntervalSource.period` is not yet supported.
=> IntervalSource: Raise descriptive error on period reset

metricq/agent.py, metricq/data_client.py, metricq/history_client.py, setup.py
The connection name has the form "(management|data|history) connection <token>".
For `aiormq<5.1.1` client_properties require an outer `{"client_properties": ...}`. and `aio-pika` depends on `aiormq<4` 😞
=> feat: add a connection name for better identification in the management UI

MANIFEST.in, setup.cfg
Requires ~current mypy master~ mypy v0.900 for `@total_ordering` to work
Maybe we should check typing in our other python projects, if everything works as expected
=> feat: add required py.typed file to support typing when used as library

metricq/history_client.py, pyproject.toml
Turns out, the HistoryClient completely lacks the ConnectionWatchdog for its history_connection.
=> Fix reconnect for HistoryClients

metricq/types.py, tests/test_types.py
Adding a similiar method `dict()` to `TimeValue` and `TimeAggregate` classes that allow to convert the types easily into a dict, which can be directly represented as JSON. Trying to stay as closely as possible to the python interface with key-values of the dict.
Fixes #121
=> feat: add `dict()` to value and aggrate types

examples/metricq_get_history.py, metricq/client.py, metricq/drain.py, metricq/subscription.py
This change allows using all Clients in with-statements. The connection will be opened and closed appropriately.
It is helpful for jupyter-notebooks, where it feels pretty opaque when the connection is running.
=> feat: Context manager support for metricq.Client

MANIFEST.in, metricq/interval_source.py, pyproject.toml, tests/test_interval_source.py
If during the processing of the `update` coroutine, an exception gets raised, the periodic `task` gets cancelled. This patch catches any exception and stops the client with the exception as reason.
Fixes #134
=> fix: exception in update zombifies IntervalSource

pyproject.toml, setup.py
=> Protobuf version guessing v2

.github/workflows/docker.yml, .github/workflows/pythonpackage.yml
The arduino/protoc action gave a rate-limit error and failed the whole
pipeline.
=> ci: replace protoc action with plain old apt-get

.github/workflows/pythonpackage.yml, docs/upgrading.rst, setup.py
fixes #162
This will need more testing. Maybe we need to use `out_dir` instead of the current working dir to find the module file. Nothing is documented, it all depends on the installation in which setup.py is invoked, local install, packaging, pip, or whatever...
=> Read protobuf version directly in setup.py

docs/api/source.rst, docs/howto/source.rst, metricq/agent.py, metricq/interval_source.py, metricq/source.py
Turns out the stop procedure of the `IntervalSource` was completely broken in the 5.0 refactoring :panda_face: .
So here's a fix, and some documentation fixes I stumbled upon.
=> Fix interval source

docs/metadata.rst, metricq/timeseries/timedelta.py
Document the new `interval` metadata that is used by the http and modbus sources
includes minor documentation improvements
=> Metadata doc update

setup.py
This merge request modifies the version parsing regex to handle cases where the major version is not specified. It will default to 3, because the value is reused later. 
https://protobuf.dev/support/version-support/
=> bug: protoc updated version naming conventions

metricq/agent.py, tests/test_agent.py
This PR adds the `Agent.url` property, which is a redacted _management_url. See #169
=> feat(agent): redacted url

docs/api/cli.rst, docs/api/index.rst, examples/metricq_client.py, examples/metricq_get_history.py, examples/metricq_get_history_raw.py, examples/metricq_pandas.py, examples/metricq_sink.py, examples/metricq_source.py, examples/metricq_synchronous_source.py, metricq/cli/__init__.py, metricq/cli/decorator.py, metricq/cli/params.py, setup.cfg, setup.py, tests/test_cli.py
Moved the Standardized CLI Params from the metrics-tools package to the Python Package.
=> feat: standardized CLI

docs/api/cli.rst, metricq/cli/__init__.py, metricq/cli/decorator.py, metricq/cli/syslog.py
Introducing the @metricq_syslog() wrapper for click commands, that configures the logger to sent to a Syslog Location (local or remote)
=> feat: metricq_syslog_option
