metricq/metricq-python

setup.py

Fix protobuf compilation

---

metricq/agent.py
metricq/client.py
metricq/version.py
setup.py

Fix package version related issues

---

metricq/client.py

Add field "hostname" to discover response

---

.gitignore
setup.py

Fixes #10 
Improves #17 by ignoring patch level

Use protobuf version from compile time

---

.github/workflows/changelog.yml
.github_changelog_generator
CHANGELOG.md
HISTORY.md

Generate changelog for closed PRs and issues

---

.github/workflows/pythonpackage.yml

Add changelog to GitHub Release

---

metricq/agent.py
metricq/connection_watchdog.py
metricq/data_client.py
metricq/interval_source.py
metricq/sink.py
setup.py

This PR fixes the reconnection issues introduced by changes in aio-pika.

Fix reconnect issues

---

.github/workflows/pythonpackage.yml
.github/workflows/release.yml

Fix release workflow

---

.pre-commit-config.yaml
metricq/client.py
metricq/source.py
pyproject.toml
setup.cfg
setup.py

This fixes some random issues that popped up mostly during #68.
Feel free to add more low-impact issues that need fixing.

Spring cleanup

---

metricq/history_client.py
metricq/types.py

Remove deprecated methods

---

docs/api/misc.rst
metricq/interval_source.py
metricq/types.py
tests/test_types.py

These are some `Timedelta` changes that came up in #80.
Still based on that branch, need to rebase once its merged.

Timedelta typing changes and proper division support

---

docs/api/exceptions.rst
docs/index.rst
docs/upgrading.rst
metricq/types.py

This should hopefully cover everything that changed for *v2.0*.
Implements #83.

Upgrading instructions

---

tools/metricq-send.py

This adds a tool that can send a single timestamp-value pair to a given metric.

Tool metric send

---

metricq/client.py
tools/metricq-discover.py

Add python version to discover response

---

metricq/agent.py

Reduce log level when handling RPCs to DEBUG

---

setup.cfg
tools/metricq-inspect.py

A tool used to get an idea about the *current* behavior of a given metric. By definition, this tool only exploits live data.

Feature: New tool metricq-inspect

---

docs/api/client-common.rst
docs/api/misc.rst
docs/conf.py
docs/howto/source.rst
docs/upgrading.rst
metricq/agent.py
metricq/client.py
metricq/connection_watchdog.py
metricq/data_client.py
metricq/history_client.py
metricq/types.py

Unify docstrings to use Google style

---

metricq/client.py

Corresponding manager PR metricq/metricq-manager#42

feat: support new hidden parameter for get_metrics RPC

---

.pre-commit-config.yaml
docs/howto/index.rst
docs/howto/project-structure.rst

Add project setup how-to

---

docs/api/drain.rst
docs/api/index.rst
docs/api/subscriber.rst
docs/howto/drain.rst
docs/howto/index.rst
examples/metricq_drain.py
metricq/__init__.py
metricq/drain.py
metricq/subscription.py

Fixes #12
Replaces #107 
Implements Drain and Subscription

Feature Drain and Subscription

---

.github/workflows/pythonpackage.yml
.gitignore
Dockerfile
docs/upgrading.rst
examples/metricq_get_history_raw.py
metricq/agent.py
metricq/connection_watchdog.py
metricq/data_client.py
metricq/history_client.py
metricq/interval_source.py
metricq/sink.py
metricq/source.py
metricq/synchronous_source.py
metricq/types.py
pyproject.toml
setup.cfg
tests/test_history_client.py
tests/test_types.py

This makes MetricQ ready for python 3.10
- Most notably, it refactors the `loop` parameter out. This part needs careful checking. (Fixes #51)
- Adds python 3.10 to test matrix in github actions
- Drops support for all Python versions <3.10

Feature: Python 3.10 support

---

examples/metricq_drain.py
setup.cfg
tests/test_interval_source.py
tests/test_source.py
tests/test_types.py

fix: pin black version and apply reformat

---

docs/howto/history-client.rst
examples/metricq_client.py
examples/metricq_get_history.py

Remaining loop parameter fixes

---

tests/test_history_client.py

fixes #151
No longer use autospec and magic mock sentinels on protobuf classes. And fix some naming capitalization.

fix: protobuf 4 tests

---

metricq/types.py

refactor: improve error message when parsing ISO 8601

---

docs/howto/sink.rst
docs/howto/source.rst
docs/upgrading.rst
examples/metricq_drain.py
examples/metricq_get_history.py
examples/metricq_get_history_raw.py
examples/metricq_sink.py
examples/metricq_source.py
examples/metricq_synchronous_source.py
metricq/agent.py
tests/test_agent.py
tests/test_history_client.py
tests/test_interval_source.py
tests/test_source.py

Agent url param

---

docs/api/subscriber.rst
docs/howto/drain.rst
examples/metricq_drain.py
metricq/subscription.py

Subscriber fixes

---

metricq/timeseries/timedelta.py
metricq/timeseries/timestamp.py
tests/test_types.py

- time types are now hashable, fixes #177
- implement Timestamp % Timedelta, fixes #178
- implement tTmedelta / Timedelta, fixes #131

Time type improvements

---

Dockerfile
metricq/agent.py
setup.cfg

feat: update docker python base image to 3.11
